<?php


namespace App\Repository;


use App\Models\Promotion;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Collection;

class PromotionRepository extends BaseRepository implements PromotionRepositoryInterface
{
    /**
     * PromotionRepository constructor.
     * @param Promotion $promotion
     */
    public function __construct(Promotion $promotion)
    {
        parent::__construct($promotion);
    }

    /**
     * @return Collection
     */
    public function getFeatured(): Collection
    {
        return $this
                    ->model
                    ->join('coupons','coupons.promotion_id','=','promotions.id')
                    ->join('coupon_qrs','coupon_qrs.coupon_code','=','coupons.code')
                    ->where('expired_at','>',''.now().'')
                    ->get();
    }

    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
